---
ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_become: yes
ansible_become_method: enable
ansible_user: pejman
ansible_password: Random7Raisi@8
ansible_become_password: Random7Raisi@8
